# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Achievements.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

from pb2_resources import OnlineService_pb2 as OnlineService__pb2

DESCRIPTOR = _descriptor.FileDescriptor(
  name='Achievements.proto',
  package='D3.Achievements',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x12\x41\x63hievements.proto\x12\x0f\x44\x33.Achievements\x1a\x13OnlineService.proto\"E\n\x17\x41\x63hievementUpdateRecord\x12\x16\n\x0e\x61\x63hievement_id\x18\x01 \x02(\x04\x12\x12\n\ncompletion\x18\x02 \x02(\x05\"l\n\x14\x43riteriaUpdateRecord\x12\"\n\x1a\x63riteria_Id_32_and_flags_8\x18\x01 \x02(\r\x12\x18\n\rstart_time_32\x18\x02 \x01(\r:\x01\x30\x12\x16\n\x0bquantity_32\x18\x03 \x01(\r:\x01\x30\"\xbf\x01\n\x08Snapshot\x12\x46\n\x14\x61\x63hievement_snapshot\x18\x01 \x03(\x0b\x32(.D3.Achievements.AchievementUpdateRecord\x12@\n\x11\x63riteria_snapshot\x18\x02 \x03(\x0b\x32%.D3.Achievements.CriteriaUpdateRecord\x12\x11\n\x06header\x18\x03 \x01(\x04:\x01\x30\x12\x16\n\x0e\x63ontent_handle\x18\x04 \x01(\t\"W\n\x11PartitionSnapshot\x12\x11\n\tpartition\x18\x01 \x01(\r\x12/\n\x0c\x61\x63hievements\x18\x02 \x01(\x0b\x32\x19.D3.Achievements.Snapshot\"%\n\x15\x41\x63hievementsResetDate\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\x03\"w\n\x1e\x41\x63hievementAwardedNotification\x12<\n\x0fgame_account_id\x18\x01 \x02(\x0b\x32#.D3.OnlineService.GameAccountHandle\x12\x17\n\x0f\x61\x63hievement_ids\x18\x02 \x03(\x04\"8\n\rDBAchievement\x12\x13\n\x0b\x61\x63hievement\x18\x01 \x02(\r\x12\x12\n\ncompletion\x18\x02 \x02(\r\"F\n\x0e\x44\x42\x41\x63hievements\x12\x34\n\x0c\x61\x63hievements\x18\x01 \x03(\x0b\x32\x1e.D3.Achievements.DBAchievement')
  ,
  dependencies=[OnlineService__pb2.DESCRIPTOR,])




_ACHIEVEMENTUPDATERECORD = _descriptor.Descriptor(
  name='AchievementUpdateRecord',
  full_name='D3.Achievements.AchievementUpdateRecord',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='achievement_id', full_name='D3.Achievements.AchievementUpdateRecord.achievement_id', index=0,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='completion', full_name='D3.Achievements.AchievementUpdateRecord.completion', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=129,
)


_CRITERIAUPDATERECORD = _descriptor.Descriptor(
  name='CriteriaUpdateRecord',
  full_name='D3.Achievements.CriteriaUpdateRecord',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='criteria_Id_32_and_flags_8', full_name='D3.Achievements.CriteriaUpdateRecord.criteria_Id_32_and_flags_8', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='start_time_32', full_name='D3.Achievements.CriteriaUpdateRecord.start_time_32', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='quantity_32', full_name='D3.Achievements.CriteriaUpdateRecord.quantity_32', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=131,
  serialized_end=239,
)


_SNAPSHOT = _descriptor.Descriptor(
  name='Snapshot',
  full_name='D3.Achievements.Snapshot',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='achievement_snapshot', full_name='D3.Achievements.Snapshot.achievement_snapshot', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='criteria_snapshot', full_name='D3.Achievements.Snapshot.criteria_snapshot', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='header', full_name='D3.Achievements.Snapshot.header', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='content_handle', full_name='D3.Achievements.Snapshot.content_handle', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=242,
  serialized_end=433,
)


_PARTITIONSNAPSHOT = _descriptor.Descriptor(
  name='PartitionSnapshot',
  full_name='D3.Achievements.PartitionSnapshot',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='partition', full_name='D3.Achievements.PartitionSnapshot.partition', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='achievements', full_name='D3.Achievements.PartitionSnapshot.achievements', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=435,
  serialized_end=522,
)


_ACHIEVEMENTSRESETDATE = _descriptor.Descriptor(
  name='AchievementsResetDate',
  full_name='D3.Achievements.AchievementsResetDate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='date', full_name='D3.Achievements.AchievementsResetDate.date', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=524,
  serialized_end=561,
)


_ACHIEVEMENTAWARDEDNOTIFICATION = _descriptor.Descriptor(
  name='AchievementAwardedNotification',
  full_name='D3.Achievements.AchievementAwardedNotification',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='game_account_id', full_name='D3.Achievements.AchievementAwardedNotification.game_account_id', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='achievement_ids', full_name='D3.Achievements.AchievementAwardedNotification.achievement_ids', index=1,
      number=2, type=4, cpp_type=4, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=563,
  serialized_end=682,
)


_DBACHIEVEMENT = _descriptor.Descriptor(
  name='DBAchievement',
  full_name='D3.Achievements.DBAchievement',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='achievement', full_name='D3.Achievements.DBAchievement.achievement', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='completion', full_name='D3.Achievements.DBAchievement.completion', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=684,
  serialized_end=740,
)


_DBACHIEVEMENTS = _descriptor.Descriptor(
  name='DBAchievements',
  full_name='D3.Achievements.DBAchievements',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='achievements', full_name='D3.Achievements.DBAchievements.achievements', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=742,
  serialized_end=812,
)

_SNAPSHOT.fields_by_name['achievement_snapshot'].message_type = _ACHIEVEMENTUPDATERECORD
_SNAPSHOT.fields_by_name['criteria_snapshot'].message_type = _CRITERIAUPDATERECORD
_PARTITIONSNAPSHOT.fields_by_name['achievements'].message_type = _SNAPSHOT
_ACHIEVEMENTAWARDEDNOTIFICATION.fields_by_name['game_account_id'].message_type = OnlineService__pb2._GAMEACCOUNTHANDLE
_DBACHIEVEMENTS.fields_by_name['achievements'].message_type = _DBACHIEVEMENT
DESCRIPTOR.message_types_by_name['AchievementUpdateRecord'] = _ACHIEVEMENTUPDATERECORD
DESCRIPTOR.message_types_by_name['CriteriaUpdateRecord'] = _CRITERIAUPDATERECORD
DESCRIPTOR.message_types_by_name['Snapshot'] = _SNAPSHOT
DESCRIPTOR.message_types_by_name['PartitionSnapshot'] = _PARTITIONSNAPSHOT
DESCRIPTOR.message_types_by_name['AchievementsResetDate'] = _ACHIEVEMENTSRESETDATE
DESCRIPTOR.message_types_by_name['AchievementAwardedNotification'] = _ACHIEVEMENTAWARDEDNOTIFICATION
DESCRIPTOR.message_types_by_name['DBAchievement'] = _DBACHIEVEMENT
DESCRIPTOR.message_types_by_name['DBAchievements'] = _DBACHIEVEMENTS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AchievementUpdateRecord = _reflection.GeneratedProtocolMessageType('AchievementUpdateRecord', (_message.Message,), dict(
  DESCRIPTOR = _ACHIEVEMENTUPDATERECORD,
  __module__ = 'Achievements_pb2'
  # @@protoc_insertion_point(class_scope:D3.Achievements.AchievementUpdateRecord)
  ))
_sym_db.RegisterMessage(AchievementUpdateRecord)

CriteriaUpdateRecord = _reflection.GeneratedProtocolMessageType('CriteriaUpdateRecord', (_message.Message,), dict(
  DESCRIPTOR = _CRITERIAUPDATERECORD,
  __module__ = 'Achievements_pb2'
  # @@protoc_insertion_point(class_scope:D3.Achievements.CriteriaUpdateRecord)
  ))
_sym_db.RegisterMessage(CriteriaUpdateRecord)

Snapshot = _reflection.GeneratedProtocolMessageType('Snapshot', (_message.Message,), dict(
  DESCRIPTOR = _SNAPSHOT,
  __module__ = 'Achievements_pb2'
  # @@protoc_insertion_point(class_scope:D3.Achievements.Snapshot)
  ))
_sym_db.RegisterMessage(Snapshot)

PartitionSnapshot = _reflection.GeneratedProtocolMessageType('PartitionSnapshot', (_message.Message,), dict(
  DESCRIPTOR = _PARTITIONSNAPSHOT,
  __module__ = 'Achievements_pb2'
  # @@protoc_insertion_point(class_scope:D3.Achievements.PartitionSnapshot)
  ))
_sym_db.RegisterMessage(PartitionSnapshot)

AchievementsResetDate = _reflection.GeneratedProtocolMessageType('AchievementsResetDate', (_message.Message,), dict(
  DESCRIPTOR = _ACHIEVEMENTSRESETDATE,
  __module__ = 'Achievements_pb2'
  # @@protoc_insertion_point(class_scope:D3.Achievements.AchievementsResetDate)
  ))
_sym_db.RegisterMessage(AchievementsResetDate)

AchievementAwardedNotification = _reflection.GeneratedProtocolMessageType('AchievementAwardedNotification', (_message.Message,), dict(
  DESCRIPTOR = _ACHIEVEMENTAWARDEDNOTIFICATION,
  __module__ = 'Achievements_pb2'
  # @@protoc_insertion_point(class_scope:D3.Achievements.AchievementAwardedNotification)
  ))
_sym_db.RegisterMessage(AchievementAwardedNotification)

DBAchievement = _reflection.GeneratedProtocolMessageType('DBAchievement', (_message.Message,), dict(
  DESCRIPTOR = _DBACHIEVEMENT,
  __module__ = 'Achievements_pb2'
  # @@protoc_insertion_point(class_scope:D3.Achievements.DBAchievement)
  ))
_sym_db.RegisterMessage(DBAchievement)

DBAchievements = _reflection.GeneratedProtocolMessageType('DBAchievements', (_message.Message,), dict(
  DESCRIPTOR = _DBACHIEVEMENTS,
  __module__ = 'Achievements_pb2'
  # @@protoc_insertion_point(class_scope:D3.Achievements.DBAchievements)
  ))
_sym_db.RegisterMessage(DBAchievements)


# @@protoc_insertion_point(module_scope)
