# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CosmeticItems.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

from pb2_resources import GameBalance_pb2 as GameBalance__pb2

DESCRIPTOR = _descriptor.FileDescriptor(
  name='CosmeticItems.proto',
  package='D3.CosmeticItems',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x13\x43osmeticItems.proto\x12\x10\x44\x33.CosmeticItems\x1a\x11GameBalance.proto\"5\n\x0c\x43osmeticItem\x12\x0c\n\x04gbid\x18\x01 \x01(\x0f\x12\x17\n\x0f\x65xpiration_time\x18\x02 \x01(\x03\"G\n\rCosmeticItems\x12\x36\n\x0e\x63osmetic_items\x18\x01 \x03(\x0b\x32\x1e.D3.CosmeticItems.CosmeticItem\"S\n\x15\x43osmeticItemSavedData\x12:\n\x0e\x63osmetic_items\x18\x01 \x01(\x0b\x32\".D3.GameBalance.BitPackedGbidArray')
  ,
  dependencies=[GameBalance__pb2.DESCRIPTOR,])




_COSMETICITEM = _descriptor.Descriptor(
  name='CosmeticItem',
  full_name='D3.CosmeticItems.CosmeticItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='gbid', full_name='D3.CosmeticItems.CosmeticItem.gbid', index=0,
      number=1, type=15, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='expiration_time', full_name='D3.CosmeticItems.CosmeticItem.expiration_time', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=113,
)


_COSMETICITEMS = _descriptor.Descriptor(
  name='CosmeticItems',
  full_name='D3.CosmeticItems.CosmeticItems',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cosmetic_items', full_name='D3.CosmeticItems.CosmeticItems.cosmetic_items', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=115,
  serialized_end=186,
)


_COSMETICITEMSAVEDDATA = _descriptor.Descriptor(
  name='CosmeticItemSavedData',
  full_name='D3.CosmeticItems.CosmeticItemSavedData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cosmetic_items', full_name='D3.CosmeticItems.CosmeticItemSavedData.cosmetic_items', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=188,
  serialized_end=271,
)

_COSMETICITEMS.fields_by_name['cosmetic_items'].message_type = _COSMETICITEM
_COSMETICITEMSAVEDDATA.fields_by_name['cosmetic_items'].message_type = GameBalance__pb2._BITPACKEDGBIDARRAY
DESCRIPTOR.message_types_by_name['CosmeticItem'] = _COSMETICITEM
DESCRIPTOR.message_types_by_name['CosmeticItems'] = _COSMETICITEMS
DESCRIPTOR.message_types_by_name['CosmeticItemSavedData'] = _COSMETICITEMSAVEDDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CosmeticItem = _reflection.GeneratedProtocolMessageType('CosmeticItem', (_message.Message,), dict(
  DESCRIPTOR = _COSMETICITEM,
  __module__ = 'CosmeticItems_pb2'
  # @@protoc_insertion_point(class_scope:D3.CosmeticItems.CosmeticItem)
  ))
_sym_db.RegisterMessage(CosmeticItem)

CosmeticItems = _reflection.GeneratedProtocolMessageType('CosmeticItems', (_message.Message,), dict(
  DESCRIPTOR = _COSMETICITEMS,
  __module__ = 'CosmeticItems_pb2'
  # @@protoc_insertion_point(class_scope:D3.CosmeticItems.CosmeticItems)
  ))
_sym_db.RegisterMessage(CosmeticItems)

CosmeticItemSavedData = _reflection.GeneratedProtocolMessageType('CosmeticItemSavedData', (_message.Message,), dict(
  DESCRIPTOR = _COSMETICITEMSAVEDDATA,
  __module__ = 'CosmeticItems_pb2'
  # @@protoc_insertion_point(class_scope:D3.CosmeticItems.CosmeticItemSavedData)
  ))
_sym_db.RegisterMessage(CosmeticItemSavedData)


# @@protoc_insertion_point(module_scope)
