# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GameBalance.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='GameBalance.proto',
  package='D3.GameBalance',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x11GameBalance.proto\x12\x0e\x44\x33.GameBalance\"9\n\x06Handle\x12\x1d\n\x11game_balance_type\x18\x01 \x02(\x11:\x02-1\x12\x10\n\x04gbid\x18\x02 \x02(\x0f:\x02-1\"]\n\x12\x42itPackedGbidArray\x12\x10\n\x08\x65lements\x18\x01 \x03(\x0f\x12\x10\n\x08\x62itfield\x18\x02 \x01(\x0c\x12#\n\x1b\x62itfield_leading_null_bytes\x18\x03 \x01(\x05')
)




_HANDLE = _descriptor.Descriptor(
  name='Handle',
  full_name='D3.GameBalance.Handle',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='game_balance_type', full_name='D3.GameBalance.Handle.game_balance_type', index=0,
      number=1, type=17, cpp_type=1, label=2,
      has_default_value=True, default_value=-1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gbid', full_name='D3.GameBalance.Handle.gbid', index=1,
      number=2, type=15, cpp_type=1, label=2,
      has_default_value=True, default_value=-1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=94,
)


_BITPACKEDGBIDARRAY = _descriptor.Descriptor(
  name='BitPackedGbidArray',
  full_name='D3.GameBalance.BitPackedGbidArray',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='elements', full_name='D3.GameBalance.BitPackedGbidArray.elements', index=0,
      number=1, type=15, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bitfield', full_name='D3.GameBalance.BitPackedGbidArray.bitfield', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bitfield_leading_null_bytes', full_name='D3.GameBalance.BitPackedGbidArray.bitfield_leading_null_bytes', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=96,
  serialized_end=189,
)

DESCRIPTOR.message_types_by_name['Handle'] = _HANDLE
DESCRIPTOR.message_types_by_name['BitPackedGbidArray'] = _BITPACKEDGBIDARRAY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Handle = _reflection.GeneratedProtocolMessageType('Handle', (_message.Message,), dict(
  DESCRIPTOR = _HANDLE,
  __module__ = 'GameBalance_pb2'
  # @@protoc_insertion_point(class_scope:D3.GameBalance.Handle)
  ))
_sym_db.RegisterMessage(Handle)

BitPackedGbidArray = _reflection.GeneratedProtocolMessageType('BitPackedGbidArray', (_message.Message,), dict(
  DESCRIPTOR = _BITPACKEDGBIDARRAY,
  __module__ = 'GameBalance_pb2'
  # @@protoc_insertion_point(class_scope:D3.GameBalance.BitPackedGbidArray)
  ))
_sym_db.RegisterMessage(BitPackedGbidArray)


# @@protoc_insertion_point(module_scope)
